[project]
name = "sidia-manolo"
version = "0.1.0-beta"
description = "Aplicativo Flet para centralização Vault Site e Digifort"
readme = "README.md"
requires-python = ">=3.14"
authors = [
    { name = "Ronivaldo", email = "ronivaldo.alpha@gmail.com" }
]
dependencies = [
    "flet[all]==1.0.3",
    "flet-charts==1.0.3",
    "sqlalchemy>=2.0",
    "pyodbc"
]

[dependency-groups]
dev = [
    "flet-cli==1.0.3",
    "flet-desktop==1.0.3",
    "flet-web==1.0.3"
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]

[tool.flet]
org = "br.com.alphaformat"
product = "Sidia Manolo"
company = "AlphaFormat"
copyright = "Copyright (C) 2023-2026 by AlphaFormat"

[tool.flet.app]
path = "src"
